[project]
name = "bookmarks-converter"
version = "1.0.2"
description = "Convert browser bookmarks files."
authors = [{ name = "Adam" }]
requires-python = ">=3.11"
readme = "README.md"
license = "MIT"
keywords = [
    "bookmarks",
    "bookmarks converter",
    "bookmarks-converter",
    "bookmarks-parser",
    "bookmarks parser",
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Utilities",
]
dependencies = [
    "beautifulsoup4>=4.14.3",
    "pytest==9.0.2",
    "SQLAlchemy>=2.0.46",
]

[project.urls]
Homepage = "https://github.com/radam9/bookmarks-converter"
Repository = "https://github.com/radam9/bookmarks-converter"

[project.scripts]
bookmarks-converter = "bookmarks_converter.cli:main"

[dependency-groups]
dev = [
    "pylint>=4.0.4",
    "pytest>=9.0.2",
    "black>=26.1.0",
    "pytest-cov>=7.0.0",
]

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
line_length = 100

[build-system]
requires = ["uv_build>=0.10.2,<0.11.0"]
build-backend = "uv_build"
